# Generated by Django 3.1.2 on 2022-12-14 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Температура'),
        ),
    ]
